name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Front-End

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests (simulado)
        run: npm test || echo "Nenhum teste encontrado"

      - name: Build projeto
        run: npm run build

      # === RELEASE & DEPLOYMENT ===

      # Passo 1: Obter a última tag
      - name: Get the latest tag and increment version
        id: get_tag
        run: |
          # Pega a última tag no repositório
          TAG=$(git describe --tags --abbrev=0)
          # Extrai o número da versão (ex: v1.0.12 -> 12)
          VERSION_NUMBER=$(echo $TAG | sed 's/v1.0.//')
          # Incrementa o número da versão
          NEW_VERSION=$((VERSION_NUMBER + 1))
          # Cria a nova tag
          NEW_TAG="v1.0.${NEW_VERSION}"
          echo "Nova tag: $NEW_TAG"
          # Passa a nova tag como output para ser usada em etapas posteriores
          echo "::set-output name=new_tag::$NEW_TAG"

      - name: Criar Release no GitHub
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.new_tag }}  # Usa a nova tag gerada
          release_name: Release ${{ steps.get_tag.outputs.new_tag }}
          draft: false
          prerelease: false

      - name: Criar Deployment no GitHub
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deploy = await github.rest.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: 'production',
              required_contexts: [],
              transient_environment: false,
              production_environment: true
            });

            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: deploy.data.id,
              state: 'success'
            });
